### ISSUE TITLE
Code for 13_diffuse_reflection is missing in the repo.

### ISSUE THREAD

**Issue by seanbaxter** [nvpro-samples/vk_mini_path_tracer#5]

**Comment by NBickford-NV** [comment]
Hi Sean!

Thanks for running through the tutorial! This is because chapter 13's code is in the [`vk_mini_path_tracer`](https://github.com/nvpro-samples/vk_mini_path_tracer/tree/main/vk_mini_path_tracer) directory, instead of the `checkpoints` directory, since it's sort of the main sample for this project in some sense.

The text in the box pointing to that chapter's code changes from the other chapters to match this (see [here](https://github.com/nvpro-samples/vk_mini_path_tracer/blob/main/docs/index.html#L5355)), but this is really easy to miss (since the previous 12 chapters' directories have almost had the same format), and at least one other person also missed this! I'll probably see if I can fix this in 2021 by adding a 13_diffuse_reflection directory with a file that says something like "see the `vk_mini_path_tracer/vk_mini_path_tracer` directory, at https://github.com/nvpro-samples/vk_mini_path_tracer/tree/main/vk_mini_path_tracer", like we currently do for [e2_performance](https://github.com/nvpro-samples/vk_mini_path_tracer/tree/main/checkpoints/e2_performance).

**Comment by seanbaxter** [comment]
I see it. Thanks.
