### ISSUE TITLE
Material 7 rendering artifact?

### ISSUE THREAD

**Issue by seanbaxter** [nvpro-samples/vk_mini_path_tracer#6]
![Screenshot at 2020-12-23 19-04-15](https://user-images.githubusercontent.com/521513/103045308-f5985200-4551-11eb-8cf4-250df4ee0c8c.png)

Is that one triangle at the bottom of the box supposed to be missing? This only effects material 7. I thought it was my shader compiler, but the same thing happens with the provided glsl. This is the material that samples gl_PrimitiveID.

**Comment by seanbaxter** [comment]
The likely explanation is that GIMP is treating pure black values as transparent.

**Comment by NBickford-NV** [comment]
Yep - I managed to reproduce this on Glimpse on Windows, and I think this is a bug in GEGL specifically when reading RLE-compressed HDR images when the exponent of a pixel is 0! I think material 7 is the only material in the tutorial that can have a reflectivity of 0 (this happens specifically for triangle 0), so that's why it's seen here. I'll create an issue on the GEGL bug tracker, link it here, and then close this issue.

**Comment by NBickford-NV** [comment]
OK, I've created a bug report at https://gitlab.gnome.org/GNOME/gegl/-/issues/275 with more details! One fun result of the way this bug works is that a workaround is to save the image back to an HDR file, then load it back in. This decompresses the image in the process, and the function that reads uncompressed HDR files doesn't have this bug.
